import datetime
from typing import Optional

from pydantic import BaseModel, EmailStr, Field

# --- User Schemas ---


class UserBase(BaseModel):
    """
    Base model for user data.
    Contains common fields that are shared across other models.
    """

    username: str = Field(
        ..., min_length=3, max_length=255, description="Unique username"
    )
    email: EmailStr = Field(..., description="Unique user email")
    first_name: Optional[str] = Field(None, max_length=100)
    last_name: Optional[str] = Field(None, max_length=100)
    phone: Optional[str] = Field(None, max_length=20)


class UserCreate(UserBase):
    """
    Schema for creating a new user.
    Inherits from UserBase and adds the password field.
    Used for the /register endpoint.
    """

    password: str = Field(
        ..., min_length=8, description="User password (will be hashed)"
    )


class UserUpdate(BaseModel):
    """
    Schema for updating an existing user's details.
    All fields are optional.
    """

    email: Optional[EmailStr] = None
    first_name: Optional[str] = Field(None, max_length=100)
    last_name: Optional[str] = Field(None, max_length=100)
    phone: Optional[str] = Field(None, max_length=20)
    # Note: Password updates should typically be a separate, dedicated endpoint.


class UserInDBBase(UserBase):
    """
    Base model for user data as it exists in the database.
    Includes fields that are auto-generated by the DB.
    """

    user_id: int
    role: str = Field(..., description="User role (e.g., user, admin)")
    created_at: datetime.datetime

    class Config:
        """
        Pydantic config to allow creating this model from database records
        (which are returned as dictionaries from our db_utils).
        """

        from_attributes = True


class User(UserInDBBase):
    """
    Schema for returning user data via the API.
    This is the "public" model. It inherits all fields from UserInDBBase
    and notably *excludes* the password_hash.
    """

    pass  # Inherits all fields from UserInDBBase


class UserInDB(UserInDBBase):
    """
    Schema representing the full user record as stored in the database.
    This model *includes* the password_hash and is used internally
    for authentication and user creation, but should *never* be
    returned from an API endpoint.
    """

    password_hash: str
